name: dbt_diary
version: "3.9"

networks:
  diary_backend_nw:
    name: diary_backend_nw
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

services:
  db-diary:
    image: postgres:latest
    container_name: db-diary
    env_file:
      - ../.env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data'
    networks:
      - diary_backend_nw
    
  redis_backend:
      image: redis:latest
      restart: always
      env_file:
        - ../.env
      entrypoint: redis-server --requirepass $${REDIS_PASSWORD}
      ports:
        - "6379:6379"
      volumes:
        - ./redis:/root/redis
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - diary_backend_nw

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - diary_backend_nw

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - diary_backend_nw

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    networks:
      - diary_backend_nw


  api-diary:
    container_name: api-diary
    hostname: api-diary
    build:
      target: dev_image
      context: ..
      dockerfile: ./docker/diary-ms.Dockerfile
    env_file: ../.env
    links:
      - kafka
      - db-diary
      - minio
      - redis_backend
    depends_on:
      db-diary:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../src/diary_ms/:/code/src/diary_ms/
      - ../.env:/code/.env
    networks:
      - diary_backend_nw
    
  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - "../.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 2
