name: dbt_user
version: "3.9"

networks:
  user_backend_nw:
    name: user_backend_nw
    driver: bridge

volumes:
  postgres-user-ms-data:
    driver: local

services:
  db-user:
    image: postgres:latest
    container_name: db-user
    env_file:
      - ../user_ms.env
    restart: always
    ports:
      - "15432:5432"
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_NAME}" ]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - postgres-user-ms-data:/var/lib/postgresql/data'
    networks:
      - user_backend_nw

  api-user:
    container_name: api-user
    build:
      target: dev_image
      context: ..
      dockerfile: ./docker/user-ms.Dockerfile
    env_file: ../user_ms.env
    environment:
      POSTGRES_HOST: db-user
    depends_on:
      db-user:
        condition: service_healthy
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - ../src/user_ms/:/code/src/user_ms/
      - ../user_ms.env:/code/user_ms.env
    networks:
      - user_backend_nw
    