global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'api-diary'
    static_configs:
      - targets: ["localhost:8000"]

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
