"""empty message

Revision ID: 5712dfc6ab07
Revises: 265617a70993
Create Date: 2024-11-27 14:27:11.592410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5712dfc6ab07'
down_revision: Union[str, None] = '265617a70993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarycard', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diarycard', 'type')
    # ### end Alembic commands ###