"""empty message

Revision ID: 265617a70993
Revises: 7414e8f9bc4c
Create Date: 2024-11-24 12:49:37.608893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '265617a70993'
down_revision: Union[str, None] = '7414e8f9bc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarycardskilllink', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diarycardskilllink', 'description')
    # ### end Alembic commands ###