version: '3.9'
name: 'api_gateway'

networks:
  diary_backend_nw:
    driver: bridge
    external: true
    name: diary_backend_nw
  user_backend_nw:
    driver: bridge
    external: true
    name: user_backend_nw

services:
  api.gateway:
    container_name: api.gateway
    build:
      dockerfile: api-gateway.Dockerfile
      context: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - api-gateway.env
    networks:
      - diary_backend_nw
      - user_backend_nw
    ports:
      - '${API_GATEWAY_PORT:-80}:80'
