worker_processes  1;
load_module modules/ngx_http_js_module.so;

events {
    worker_connections  1024;
}

http {
    js_import /etc/nginx/conf.d/oauth2.js; # Location of JavaScript code

    server {
        listen 80;
        server_name _;

        location / {
            return 200;
        }

        location /api/v1/auth/ {
            auth_request off;
            proxy_set_header Host $host;
            proxy_pass https://api-user:5000;
        }

        location /api/v1/diary {
            auth_request /api/v1/auth/jwt/refresh;
            error_page 403 /403.json;
            error_page 401 /401.json;
            error_page 500 /401.json;
            error_page 404 /404.json;

            location ~ diary {
                proxy_set_header Host $host;
                proxy_pass http://api-diary:8000;
            }
        }

        location /404.json {
            return 404 '{"error": "Requested resource not found"}';
        }

        location /401.json {
            return 401 '{"error": "Unauthenticated"}';
        }

        location /403.json {
            return 403 '{"error": "Forbidden"}';
        }

        location = api/v1/auth/jwt/refresh {
            internal;
            js_content verifyAccessToken;
        }

        location /api/auth/jwt/refresh {
            internal;
            proxy_method      GET;
            proxy_set_header Host $host;
            proxy_set_header  Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_pass        http://api-user:5000/auth/jwt/refresh;
            proxy_set_header Content-Length "";

            proxy_ignore_headers  Cache-Control Expires Set-Cookie;
        }
    }
}
