"""empty message

Revision ID: 41c8623c9fde
Revises: a936be7af5ac
Create Date: 2025-01-27 15:45:01.807736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c8623c9fde'
down_revision: Union[str, None] = 'a936be7af5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_card_skill', sa.Column('situation', sa.String(length=100), nullable=True))
    op.drop_column('diary_card_skill', 'description')
    op.add_column('skills', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'description')
    op.add_column('diary_card_skill', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('diary_card_skill', 'situation')
    # ### end Alembic commands ###
