"""empty message

Revision ID: 1f039503d799
Revises: 
Create Date: 2025-01-17 21:57:32.103554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f039503d799'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('date_of_entry', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dosage', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('DBT', 'RO_DBT', name='skill_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('urge', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_card_emotion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diary_card_id', sa.UUID(), nullable=False),
    sa.Column('emotion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id', 'diary_card_id', 'emotion_id')
    )
    op.create_table('diary_card_medicament',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diary_card_id', sa.UUID(), nullable=False),
    sa.Column('medicament_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.PrimaryKeyConstraint('id', 'diary_card_id', 'medicament_id')
    )
    op.create_table('diary_card_skill',
    sa.Column('diary_card_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('diary_card_id', 'skill_id')
    )
    op.create_table('diary_card_target',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diary_card_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id', 'diary_card_id', 'target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_card_target')
    op.drop_table('diary_card_skill')
    op.drop_table('diary_card_medicament')
    op.drop_table('diary_card_emotion')
    op.drop_table('targets')
    op.drop_table('skills')
    op.drop_table('medicaments')
    op.drop_table('emotions')
    op.drop_table('diary_cards')
    # ### end Alembic commands ###
