"""empty message

Revision ID: a2420fbaad70
Revises: 880c85839e70
Create Date: 2025-03-29 20:29:20.653392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2420fbaad70'
down_revision: Union[str, None] = '880c85839e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('action', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'action')
    # ### end Alembic commands ###
