"""empty message

Revision ID: 5b36c819198f
Revises: 2a159e3ca105
Create Date: 2025-02-13 23:00:33.386023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b36c819198f'
down_revision: Union[str, None] = '2a159e3ca105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('diary_card_emotion_diary_card_id_fkey', 'diary_card_emotion', type_='foreignkey')
    op.drop_constraint('diary_card_emotion_emotion_id_fkey', 'diary_card_emotion', type_='foreignkey')
    op.create_foreign_key(None, 'diary_card_emotion', 'diary_cards', ['diary_card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diary_card_emotion', 'emotions', ['emotion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('diary_card_medicament_diary_card_id_fkey', 'diary_card_medicament', type_='foreignkey')
    op.drop_constraint('diary_card_medicament_medicament_id_fkey', 'diary_card_medicament', type_='foreignkey')
    op.create_foreign_key(None, 'diary_card_medicament', 'diary_cards', ['diary_card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diary_card_medicament', 'medicaments', ['medicament_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('diary_card_skill_skill_id_fkey', 'diary_card_skill', type_='foreignkey')
    op.drop_constraint('diary_card_skill_diary_card_id_fkey', 'diary_card_skill', type_='foreignkey')
    op.create_foreign_key(None, 'diary_card_skill', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diary_card_skill', 'diary_cards', ['diary_card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('diary_card_target_diary_card_id_fkey', 'diary_card_target', type_='foreignkey')
    op.drop_constraint('diary_card_target_target_id_fkey', 'diary_card_target', type_='foreignkey')
    op.create_foreign_key(None, 'diary_card_target', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diary_card_target', 'diary_cards', ['diary_card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diary_card_target', type_='foreignkey')
    op.drop_constraint(None, 'diary_card_target', type_='foreignkey')
    op.create_foreign_key('diary_card_target_target_id_fkey', 'diary_card_target', 'targets', ['target_id'], ['id'])
    op.create_foreign_key('diary_card_target_diary_card_id_fkey', 'diary_card_target', 'diary_cards', ['diary_card_id'], ['id'])
    op.drop_constraint(None, 'diary_card_skill', type_='foreignkey')
    op.drop_constraint(None, 'diary_card_skill', type_='foreignkey')
    op.create_foreign_key('diary_card_skill_diary_card_id_fkey', 'diary_card_skill', 'diary_cards', ['diary_card_id'], ['id'])
    op.create_foreign_key('diary_card_skill_skill_id_fkey', 'diary_card_skill', 'skills', ['skill_id'], ['id'])
    op.drop_constraint(None, 'diary_card_medicament', type_='foreignkey')
    op.drop_constraint(None, 'diary_card_medicament', type_='foreignkey')
    op.create_foreign_key('diary_card_medicament_medicament_id_fkey', 'diary_card_medicament', 'medicaments', ['medicament_id'], ['id'])
    op.create_foreign_key('diary_card_medicament_diary_card_id_fkey', 'diary_card_medicament', 'diary_cards', ['diary_card_id'], ['id'])
    op.drop_constraint(None, 'diary_card_emotion', type_='foreignkey')
    op.drop_constraint(None, 'diary_card_emotion', type_='foreignkey')
    op.create_foreign_key('diary_card_emotion_emotion_id_fkey', 'diary_card_emotion', 'emotions', ['emotion_id'], ['id'])
    op.create_foreign_key('diary_card_emotion_diary_card_id_fkey', 'diary_card_emotion', 'diary_cards', ['diary_card_id'], ['id'])
    # ### end Alembic commands ###
