"""empty message

Revision ID: 98939b55f313
Revises: a2420fbaad70
Create Date: 2025-04-18 20:42:03.264011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98939b55f313'
down_revision: Union[str, None] = 'a2420fbaad70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_card_skill', sa.Column('usage', sa.String(length=200), nullable=True))
    op.add_column('diary_card_skill', sa.Column('effectiveness', sa.SmallInteger(), nullable=True))
    op.drop_column('diary_card_skill', 'situation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_card_skill', sa.Column('situation', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('diary_card_skill', 'effectiveness')
    op.drop_column('diary_card_skill', 'usage')
    # ### end Alembic commands ###
