"""empty message

Revision ID: 427607364bdb
Revises: 1f039503d799
Create Date: 2025-01-17 22:27:28.600724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427607364bdb'
down_revision: Union[str, None] = '1f039503d799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_card_emotion', 'id')
    op.drop_column('diary_card_medicament', 'id')
    op.drop_column('diary_card_target', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_card_target', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('diary_card_medicament', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('diary_card_emotion', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
