"""empty message

Revision ID: 837759b93f61
Revises: 98939b55f313
Create Date: 2025-04-23 23:20:45.795851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837759b93f61'
down_revision: Union[str, None] = '98939b55f313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_card_target', sa.Column('urge_intensity', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_card_target', 'urge_intensity')
    # ### end Alembic commands ###
