"""Initial.

Revision ID: 86a4f79f2040
Revises: 
Create Date: 2024-12-24 12:35:30.070973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a4f79f2040'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_of_entry', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotions',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicaments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('dosage', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('urge', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_card_emotion',
    sa.Column('diary_card_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('diary_card_id', 'skill_id')
    )
    op.create_table('diary_card_medicament',
    sa.Column('diary_card_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['medicaments.id'], ),
    sa.PrimaryKeyConstraint('diary_card_id', 'skill_id')
    )
    op.create_table('diary_card_skill',
    sa.Column('diary_card_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('diary_card_id', 'skill_id')
    )
    op.create_table('diary_card_target',
    sa.Column('diary_card_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['diary_card_id'], ['diary_cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('diary_card_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_card_target')
    op.drop_table('diary_card_skill')
    op.drop_table('diary_card_medicament')
    op.drop_table('diary_card_emotion')
    op.drop_table('targets')
    op.drop_table('skills')
    op.drop_table('medicaments')
    op.drop_table('emotions')
    op.drop_table('diary_cards')
    # ### end Alembic commands ###
